spring:
  application:
    name: open-book

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        temp.use_jdbc_metadata_defaults: false

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

books:
  aladin:
    api:
      TTBKey: "ttbkdh6102309002"
  kakao:
    api:
      kakaoAK: "21b493af0e8d30d5c1873e01a2346b69"
  naver:
    api:
      client-id: "a0P9aNvfYozXyTRfErny"
      client-secret: "xfZqDNxeXS"
